[package]
name = "rithmic-client"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.87"
dotenv = "0.15.0"
futures-util = "0.3.31"
prost = "0.13.5"
tokio = { version = "1.44.0", features = ["full"] }
tokio-tungstenite = { version = "0.26.2", features = ["rustls-tls-native-roots"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
base64 = "0.22.1"
tungstenite = "0.26.2"
bytes = "1.10.1"
http = "1.1.0"
tokio-rustls = "0.26.2"
anyhow = "1.0.89"
hyper-util = { version = "0.1.10", features = ["tokio"] }
hyper = { version = "1.6.0", features = ["client", "http1"] }
http-body-util = "0.1.3"


[build-dependencies]
prost-build = "0.13.5"
